project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!slides/"
  resources:
    - "slides/"
    - "img/"

website:
  title: "Data science for linguists"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: setup.qmd
        text: Set-up
      - text: Slides
        menu:
          - href: "01.qmd"
            text: "Day 1"
          - href: ""
            text: "Day 2"
          - href: ""
            text: "Day 3"

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

callout-icon: false

