---
title: "Pre-workshop set-up"
editor: source
---

Please, follow these instructions to get ready **before** the workshop.

## Pre-requisites

First, make sure you have installed or updated the following software.

- The **latest version of R** (<https://cloud.r-project.org>).
- The **latest version of RStudio** (<https://www.rstudio.com/products/rstudio/download/#download>).
- Your **operating system is up-to-date**.

## Install R packages

Now you will need to install the following packages:

- tidyverse
- lme4
- sjPlot
- remotes
- ds4ling

You can do so by copying and pasting the following code into the console:

``` r
install.packages(c("tidyverse", "lme4", "sjPlot", "remotes"))
remotes::install_github("jvcasillas/ds4ling")
```

The `tidyverse` package will install a bunch of other packages that are useful for data tidying/visualization.
We will use `lme4` to fit mixed effects models and `sjPlot` to summarize/visualize them.
The `remotes` package allows us to install packages directly from github, like the `ds4ling` package specified in line 2.
This package provides some useful helper functions we will use in our examples.
It should take a few minutes to install the packages, depending on your system and configuration.
If at any point you get asked about installing extra packages or software, please do so.

## Troubleshoot

If you have issues with any of these steps, please get in touch with Joseph or submit an issue [here](https://github.com/ds4ling/workshops/issues).
